### PR TITLE
Add support for rails 6

### PR DESCRIPTION
**Pull request by yosiat**
Rails 6 added another parameter for migrations which is schema migrations

### CODE REVIEW

**Comment by 4ndv** [comment]
Also seen issue with `rake db:generate_trigger_migration` command, when it not detecting some models

**Comment by yosiat** [comment]
@4ndv do you have more details? maybe some reproducible test?

@jenseng can you please review?

**Comment by jenseng** [comment]
Hi @yosiat, thanks for the CR! It looks like the Travis build failed, so we should figure out what's happening there. I retriggered it and it [failed again](https://travis-ci.org/jenseng/hair_trigger/builds/565099855?utm_source=github_status&utm_medium=notification). I also retriggered the latest master build just to be sure and [that passed](https://travis-ci.org/jenseng/hair_trigger/builds/490407157).

It's not clear why your code would cause that failure (can't connect to MySQL or PostgreSQL in the tests), but we should resolve that before merging. I'll dig a little deeper to see if I can figure it out.

In addition to getting the tests passing, I think we should also update .travis.yml as part of this CR so that the CI build also runs tests using the new `gemfiles/activerecord_6.0.gemfile` you added.

**Comment by yosiat** [comment]
yo @jenseng ,

I updated the travis.yml to add rails 6 gemfile and updated the gemfile to use the stable release

**Comment by DmitryTsepelev** [comment]
Hi @yosiat and @jenseng, looks like there is one more [PR](https://github.com/jenseng/hair_trigger/pull/83) with a Rails 6 support and passing tests 🙂 Maybe we could combine them in some way

**Comment by yosiat** [comment]
@DmitryTsepelev thanks for pointing out the other PR.

@jenseng I think @ojab PR's is better and does the same, so I am closing this PR.

**Comment by jenseng** [comment]
@yosiat thanks for your work on this, I've merged the other PR and will be pushing a new release momentarily

**Pull request closed without merging**
