### PR TITLE
Fix Ruby 2.7 warnings on Proc.new

### PR DESCRIPTION
**Pull request by erikaxel**
This fixes issue #89 Ruby 2.7 gives warning on use of Proc.new:
`hair_trigger/builder.rb:145: warning: Capturing the given block using Proc.new is deprecated; use &blockinstead hair_trigger/builder.rb:155: warning: Capturing the given block using Proc.new is deprecated; use&block instead
`

### CODE REVIEW

**Comment by liaden** [comment]
Referenced this in my Gemfile and ran tests. Warnings are gone and my tests stayed green.

**Comment by adrijere** [comment]
Same here, all green, thanks for the job done :v:

**Comment by imaqsood** [comment]
@jenseng 
@jenseng 
@jenseng 

https://github.com/jenseng/hair_trigger/pull/91/commits/253c0b145f9be98f31e23591df6fc209bd19c4ce

**Comment by manuelmeurer** [comment]
@jenseng Could you merge this and release a new version please? Thanks! 🙇

**Comment by adrijere** [comment]
Any update @jenseng :) ?

**Comment by hrs113355** [comment]
@jenseng It would be great to have this in a new version 🙏

**Comment by Laykou** [comment]
Calling `Proc.new` without block is not working in Ruby 3.0. 

Error:

```
StandardError: An error has occurred, all later migrations canceled:

tried to create Proc object without a block
```

@jenseng Could you please merge this and release as a new version? Thank you!

**Comment by Laykou** [comment]
Hi guys, I see @jenseng is not responding and last commit in master is since Sep 2019. Do you think this repo is abandoned and we should do our own fork? It's unfortunate, since it looked like a solid gem :'(

**Comment by jenseng** [comment]
👋  sorry everyone, my github notifications were off and I haven't been using this gem (or even ruby) in years 😬  ... I'll get these merged and released shortly, but if anyone wants to help take over maintaining this gem moving forward I'm totally open to it 🤗

**Comment by jenseng** [comment]
released in v0.2.24

**Pull request merged**
